use anyhow::{Context, Result};
use tokio::fs;
use tokio::process::Command;

use crate::config::WikiConfig;
use crate::note_ops;

/// Minimal `include.typ` placed at the wiki root.
///
/// Provides only what zk-lsp itself requires:
///   - `zettel`    — render function called by every note
///   - `zk_entry` — called by `link.typ` to include each note
///
/// Extend this file freely with your own imports and styling.
const INCLUDE_TYP: &str = r#"// zk-lsp include — extend with your own imports and styling

/// Render a single zettel.
/// `metadata` is the TOML-parsed table from the note header.
#let zettel(metadata: none, body) = body

/// Include one note into the compiled document.
/// Called automatically by link.typ.
#let zk_entry(id, path) = {
  include path
}
"#;

/// Human-editable entry point for the compiled wiki document.
/// Import link.typ (auto-generated) here and add any manual content around it.
const INDEX_TYP: &str = r#"// index.typ — editable entry point for your wiki.
// Compile this file with Typst to produce the full document.
//
// link.typ is auto-generated by zk-lsp and lists every note.
// Edit *this* file freely; do not edit link.typ by hand.

#import "include.typ": *

#include "link.typ"
"#;

const GITIGNORE: &str = "*.pdf\n";

/// Initialise a fresh wiki at `config.root`.
///
/// Steps:
///   1. Create root + `note/` directory.
///   2. Write `include.typ` and an empty `link.typ`.
///   3. Write `.gitignore`.
///   4. `git init` (if git is available; non-fatal on failure).
///   5. Create one sample note via `note_ops::create_note`.
pub async fn init_wiki(config: &WikiConfig) -> Result<()> {
    let root = &config.root;

    // 1. Directories
    fs::create_dir_all(&config.note_dir)
        .await
        .with_context(|| format!("creating note dir {}", config.note_dir.display()))?;

    // 2. include.typ — skip if already present
    let include_path = root.join("include.typ");
    if !include_path.exists() {
        fs::write(&include_path, INCLUDE_TYP)
            .await
            .with_context(|| format!("writing {}", include_path.display()))?;
        eprintln!("  created  include.typ");
    } else {
        eprintln!("  exists   include.typ (skipped)");
    }

    // index.typ — human-editable entry point
    let index_path = root.join("index.typ");
    if !index_path.exists() {
        fs::write(&index_path, INDEX_TYP)
            .await
            .with_context(|| format!("writing {}", index_path.display()))?;
        eprintln!("  created  index.typ");
    } else {
        eprintln!("  exists   index.typ (skipped)");
    }

    // link.typ is created implicitly by note_ops::create_note → link_gen::add_entry,
    // but we touch it early so `git init` picks it up in the initial commit listing.
    let link_path = &config.link_file;
    if !link_path.exists() {
        fs::write(link_path, "#import \"include.typ\": *\n// Auto-generated by zk-lsp — do not edit manually.\n// Run `zk-lsp generate` to rebuild.\n\n")
            .await
            .with_context(|| format!("writing {}", link_path.display()))?;
        eprintln!("  created  link.typ");
    } else {
        eprintln!("  exists   link.typ (skipped)");
    }

    // 3. .gitignore
    let gitignore_path = root.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(&gitignore_path, GITIGNORE)
            .await
            .with_context(|| format!("writing {}", gitignore_path.display()))?;
        eprintln!("  created  .gitignore");
    } else {
        eprintln!("  exists   .gitignore (skipped)");
    }

    // 4. git init (best-effort)
    let git_dir = root.join(".git");
    if !git_dir.exists() {
        match Command::new("git").arg("init").arg(root).output().await {
            Ok(out) if out.status.success() => eprintln!("  git init  {}", root.display()),
            Ok(out) => eprintln!(
                "  git init failed: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            ),
            Err(e) => eprintln!("  git not found, skipping: {e}"),
        }
    } else {
        eprintln!("  exists   .git (skipped)");
    }

    // 5. Sample note
    let note_path = note_ops::create_note(config).await?;
    eprintln!("  created  {}", note_path.display());

    eprintln!("\nWiki initialised at {}", root.display());
    eprintln!("Next: open {} and start writing.", note_path.display());
    Ok(())
}
